MODULE:=tomsfastmath

CFLAGS += -DTFM_NO_ASM

DIRS += addsub
DIRS += bin
DIRS += bit
DIRS += divide
DIRS += exptmod
DIRS += misc
DIRS += mont
DIRS += mul
DIRS += numtheory
DIRS += sqr

include $(RIOTBASE)/Makefile.base
